LPORDDIR   = $(topdir)/PORD/lib/
IPORD      = -I$(topdir)/PORD/include/
LPORD      = -L$(LPORDDIR) -lpord
PLAT       = 
IMETIS = -I/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/include
LMETIS = -Wl,-rpath,/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -lmetis
IPARMETIS = -I/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/include
LPARMETIS = -Wl,-rpath,/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -lparmetis
ORDERINGSC = -Dpord -Dmetis -Dparmetis
ORDERINGSF = -Dpord -Dmetis -Dparmetis
LORDERINGS  = $(LPARMETIS) $(LMETIS) $(LPORD) $(LSCOTCH)
IORDERINGSC = $(IPARMETIS) $(IMETIS) $(IPORD) $(ISCOTCH)
IORDERINGSF = $(ISCOTCH)
RM = /bin/rm -f
CC = /Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/bin/mpicc
OPTC    = -fstack-protector -fno-stack-check -Qunused-arguments -g -O3 -fno-common -Wno-implicit-function-declaration
OUTC = -o 
FC = /Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/bin/mpif90
FL = /Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/bin/mpif90
OPTF    = -ffree-line-length-0 -Wno-lto-type-mismatch -g -O -fallow-argument-mismatch
OUTF = -o 
CDEFS   = -DAdd_
AR      = /usr/bin/ar cr 
LIBEXT  = .a
RANLIB  = /usr/bin/ranlib -c
SCALAP  = -Wl,-rpath,/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -lscalapack
INCPAR  = -I/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/include
LIBPAR  = $(SCALAP) 
INCSEQ  = -I$(topdir)/libseq
LIBSEQ  =  $(LAPACK) -L$(topdir)/libseq -lmpiseq
LIBBLAS = -Wl,-rpath,/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -lflapack -Wl,-rpath,/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -lfblas -lc++ -ldl -Wl,-rpath,/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/MyDocuments-Local/trunk-jpl/externalpackages/petsc/install/lib -lmpifort -lmpi -lpmpi -lgfortran -Wl,-rpath,/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin21/12 -L/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin21/12 -Wl,-rpath,/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc -L/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc -Wl,-rpath,/Users/kasra/Documents/trunk-jpl/externalpackages/petsc/install/lib -L/Users/kasra/Documents/trunk-jpl/externalpackages/petsc/install/lib -Wl,-rpath,/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current -L/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current -lgfortran -lemutls_w -lquadmath -Wl,-rpath,/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin21/12 -Wl,-rpath,/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc -Wl,-rpath,/Users/kasra/Documents/trunk-jpl/externalpackages/petsc/install/lib -Wl,-rpath,/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current
OPTL    = -Wl,-no_compact_unwind -Wl,-bind_at_load -Wl,-multiply_defined,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first -Wl,-no_compact_unwind -Wl,-bind_at_load -Wl,-multiply_defined,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first -Wl,-no_compact_unwind  -Wall -Wwrite-strings -Wno-unknown-pragmas -fstack-protector -fno-stack-check -Qunused-arguments -fvisibility=hidden -g -O3
INCS = $(INCPAR)
LIBS = $(LIBPAR)
LIBSEQNEEDED =
